### ISSUE TITLE
NKK logo overlaps with "my favorite organizations" design on Favorites section

### ISSUE THREAD

**Issue by jullianne-alberta** [jaredblase/arw-2021#10]
### Summary
- Placement of NKK logo overlaps with blue part of "my favorite organizations" design on Favorites section 
- Edit: I just saw that this overlap also appears when DLSU-SEASON or ArCG is added to the favorites section. I'm now unsure if it is actually a design issue. 

### Steps to Reproduce
1. Go to website. 
2. Click NKK logo. 
3. Heart favorites in NKK page.  
4. Go to Favorites section. 

### Visual Proof 
![249627328_269890241752836_6219811914371884292_n](https://user-images.githubusercontent.com/92969612/139459003-1b1013fa-ca9a-4488-adae-44da27e5a199.jpg)

### Expected Results:
- Design should not overlap with the organization's logo

### Actual Results:
- Design overlaps with the organization's logo 

| Additional Information | |
| ----------- | ----------- |
| Device    | Mobile|
| Platform |Opera|
| Operating System |Android version 9|

**Comment by jaredblase** [comment]
This bug has been addressed. Please recheck and close this issue. Thanks!
