### ISSUE TITLE
Missing Tagline for VA's org page

### ISSUE THREAD

**Issue by happy-the-cat** [jaredblase/arw-2021#12]
### Summary
The tagline for VA (Viridis Arcus Esports)’ that should be at the bottom of the page is missing.

### Steps to Reproduce
1. Click the drop-down menu on the top left and select Organizations;
2. Navigate down to the ASPIRE section and press VA;
3. Scroll to the bottom of VA's org page.

### Visual Proof
![248216337_411598443779869_7319860767210812067_n](https://user-images.githubusercontent.com/77759561/142517148-566efd14-8574-4e4b-a83f-4f3c8455acf2.jpg)

### Expected Results:
Should have some tagline after the Register and Favorites button.

### Actual Results:
No tagline after the two buttons.

| Additional Information | |
| ----------- | ----------- |
| Device    | Mobile |
| Platform | Safari |
| Operating System | iOS |

**Comment by jaredblase** [comment]
Some of the organizations, including VA, do not have taglines. Thank you!
