### ISSUE TITLE
Gforms Link not aligned with the Org Page

### ISSUE THREAD

**Issue by hyerinssi** [jaredblase/arw-2021#14]
### Summary 
TEAMCOMM's register button takes you to ACCESS google forms.

### Steps to Reproduce
1. Go to Organizations Page
2. Under CAP13, click TEAMCOMM
3. Click Register button
### Visual Proof
![image](https://user-images.githubusercontent.com/91784947/142728965-efa20543-f4d9-45dc-a99f-50f26f7e0845.png)
![image](https://user-images.githubusercontent.com/91784947/142728971-851d92a5-83cc-44a6-8803-e7f3dd15f421.png)

### Expected Results
- The link should redirect to TEAMCOM's gforms link 

### Actual Results
- The link redirected to ACCESS' gform link

| Additional Information |
| ------------ |------------- |
| Device | Desktop |
| Platform | Opera |
| Operating System | Windows 10 |

**Comment by Zet-Warden** [comment]
Fixed. Please make sure it's also fixed on your end then close this issue once it's resolved. Thank you.
