### ISSUE TITLE
Placement of "Seek and Discover" and Logo appear displaced on Q&A tab when clicking "ask a question" or "send us your thoughts" box 

### ISSUE THREAD

**Issue by jullianne-alberta** [jaredblase/arw-2021#9]
### Summary
- Placement of "Seek and Discover" and Logo appear displaced on Q&A tab when clicking "ask a question" and/or "send us your thoughts" boxes 

### Steps to Reproduce
1. Go to website. 
2. Click Questions & Feedback. 
3. Click "Ask a question" box or Click "send us your thoughts" box. 
4. Scroll to the bottom part of the page 

### Visual Proof 
I'm not sure why but github won't process the pictures I try to upload so I'm attaching gdrive links for the visual proof. 
1.  When one is not clicking the "ask a question" box or "send us your thoughts" box and scrolls to the bottom part of the page, the placement of the logo is as seen in the link. Link: https://drive.google.com/file/d/1oNZqXiCo6FH6NS8Okt8WUWZfHU0EN1Es/view?usp=sharing
2.  Clicking the "ask a question" box or "send us your thoughts" box and scrolling to the bottom part of the page would make the logo appear as seen in the link. Link: https://drive.google.com/file/d/1OzXw8Pi1PKpqw-AHtvuwMTQQAAwjw5AP/view?usp=sharing

### Expected Results:
- Logo should be at the end of the page

### Actual Results:
- Logo appears not to be placed at the end of the page 

| Additional Information | |
| ----------- | ----------- |
| Device    | Mobile|
| Platform |Opera|
| Operating System |Android version 9|

**Comment by jaredblase** [comment]
I have recently tested on my Opera mobile on Android 10 and it seems that the issue has been fixed. Can you check if it's alright on your end? Thank you!
